# Generated by Django 2.2.1 on 2019-09-19 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='payment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_desc', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('order_qty', models.IntegerField()),
                ('order_amount', models.FloatField()),
                ('order_created_date', models.DateTimeField(auto_now=True)),
                ('order_notes', models.CharField(max_length=1000)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='order_entry.item')),
                ('order_payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order_entry.payment_type')),
            ],
        ),
    ]
