# Generated by Django 2.2.1 on 2019-09-19 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_effective_from', models.DateField()),
                ('price_effective_to', models.DateField()),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_entry.item')),
            ],
        ),
    ]
