# Generated by Django 2.2.1 on 2019-09-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_entry', '0002_item_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='order_entry_item',
        ),
        migrations.AlterModelTable(
            name='item_price',
            table='order_entry_item_price',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order_entry_order',
        ),
        migrations.AlterModelTable(
            name='payment_type',
            table='order_entry_payment_type',
        ),
    ]
