# Generated by Django 2.2.1 on 2019-09-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_entry', '0003_auto_20190918_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='order_entry.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='order_entry.payment_type'),
        ),
    ]
