# Generated by Django 2.2.1 on 2019-09-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'order_api_table',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
